### PR TITLE
8.5 release date

### PR DESCRIPTION
**Pull request by Silvakabe**

### CODE REVIEW

**Comment by abheekda1** [comment]
I think this should be good but I"m gonna wait on Moonded to merge it.

**Comment by Silvakabe** [comment]
Sounds good to me 👍

**Comment by abheekda1** [comment]
Hey @silverlags one thing -- when making PRs try to do them on a different branch than main. That way you can keep main on track with the upstream and create new branches for different changes.

**Comment by Silvakabe** [comment]
Got it, Thanks for the heads up @ADawesomeguy !

**Pull request merged**
